apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- mutatingwebhookconfiguration.yaml
- ../common
- ../crd/default
images:
- name: controller
  newName: quay.io/dynatrace/dynatrace-operator
  newTag: snapshot-refactor-remove-related-image-env
