apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-oneagent-operator
  labels:
    dynatrace: operator
    operator: oneagent
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - dynatrace-oneagent-config
      - dynatrace-oneagent-pull-secret
    verbs:
      - get
      - update
      - delete
