apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dynatrace-oneagent-webhook
  namespace: dynatrace
  labels:
    dynatrace.com/operator: oneagent
    internal.oneagent.dynatrace.com/component: webhook
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - dynatrace.com
    resources:
      - oneagents
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - dynatrace-oneagent-webhook
    verbs:
      - use
