apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: dynatrace-oneagent-unprivileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-oneagent-unprivileged
subjects:
- kind: ServiceAccount
  name: dynatrace-oneagent-unprivileged
  namespace: dynatrace
