apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: dynatrace-oneagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dynatrace-oneagent
subjects:
- kind: ServiceAccount
  name: dynatrace-oneagent
  namespace: dynatrace
