apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: dynatrace-oneagent-unprivileged
rules:
- apiGroups:
  - policy
  resourceNames:
  - dynatrace-oneagent-unprivileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
