apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../openshift
- ../samples
images:
- name: quay.io/dynatrace/dynatrace-oneagent-operator:snapshot
  newName: registry.connect.redhat.com/dynatrace/dynatrace-oneagent-operator
