// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&OneAgent{}, func(obj interface{}) { SetObjectDefaults_OneAgent(obj.(*OneAgent)) })
	scheme.AddTypeDefaultingFunc(&OneAgentList{}, func(obj interface{}) { SetObjectDefaults_OneAgentList(obj.(*OneAgentList)) })
	return nil
}

func SetObjectDefaults_OneAgent(in *OneAgent) {
	SetDefaults_OneAgentSpec(&in.Spec)
}

func SetObjectDefaults_OneAgentList(in *OneAgentList) {
	for i := range in.Items {
		a := &in.Items[i]
		SetObjectDefaults_OneAgent(a)
	}
}
