apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynatrace-oneagent-operator
  labels:
    dynatrace: operator
    operator: oneagent
subjects:
  - kind: ServiceAccount
    name: dynatrace-oneagent-operator
    namespace: dynatrace
roleRef:
  kind: ClusterRole
  name: dynatrace-oneagent-operator
  apiGroup: rbac.authorization.k8s.io
