apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynatrace-oneagent-operator
  labels:
    dynatrace: operator
    operator: oneagent
rules:
  - apiGroups:
      - "" # "" indicates the core API group
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
