apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dynatrace-oneagent-webhook
  namespace: dynatrace
  labels:
    dynatrace.com/operator: oneagent
    internal.oneagent.dynatrace.com/component: webhook
subjects:
  - kind: ServiceAccount
    name: dynatrace-oneagent-webhook
    namespace: dynatrace
roleRef:
  kind: Role
  name: dynatrace-oneagent-webhook
  apiGroup: rbac.authorization.k8s.io
