apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podsecuritypolicy-oneagent.yaml
- podsecuritypolicy-oneagent-unprivileged.yaml
- podsecuritypolicy-operator.yaml
- podsecuritypolicy-webhook.yaml
- role-oneagent.yaml
- role-oneagent-unprivileged.yaml
- rolebinding-oneagent.yaml
- rolebinding-oneagent-unprivileged.yaml
bases:
  - ../common
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: dynatrace-oneagent-operator
      namespace: dynatrace
    path: role-operator-patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: dynatrace-oneagent-webhook
      namespace: dynatrace
    path: role-webhook-patch.yaml
