apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- podsecuritypolicy-oneagent.yaml
- podsecuritypolicy-operator.yaml
- podsecuritypolicy-webhook.yaml
- role-oneagent.yaml
- rolebinding-oneagent.yaml
bases:
  - ../common
patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: dynatrace-oneagent-operator
      namespace: dynatrace
    patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - policy
          resources:
            - podsecuritypolicies
          resourceNames:
            - dynatrace-oneagent-operator
          verbs:
            - use
